---
apiVersion: 1

deleteDatasources:
- name: gdev-influxdb-telegraf
  orgId: 1

datasources:
- name: gdev-influxdb-telegraf
  type: influxdb
  access: proxy
  database: telegraf
  user: grafana
  url: http://influxdb:8086
  jsonData:
    timeInterval: "1s"
  secureJsonData:
    password: grafana