version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.7
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - $PWD/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:6.1.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    links:
      - influxdb
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:1.12.2
    links:
      - influxdb
    #network_mode: "host"
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf
    #  - /var/run/docker.sock:/var/run/docker.sock
    restart: always